spring:
  h2:
    console:
      enabled: true
      settings:
      # Enable remote access.
        web-allow-others: true
  output:
    ansi:
      enabled: always


---

cafci:
  api:
    url: api.cafci.org.ar